spring.application.name=backend
server.port=${PORT:8080}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=test

# JWT Configuration
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=86400000
